<?php

namespace Dk\RulesetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RulesetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RulesetRepository extends EntityRepository
{
}
