<?php

namespace Dk\Bundle\SystemBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Dk\Bundle\SystemBundle\Entity\Player;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignRepository extends EntityRepository
{
     /**
     * Get campaigns owned by a player
     * @return mixed
     */
    public function findMasterCampaigns(Player $owner)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT c FROM DkSystemBundle:Campaign c
                WHERE c.owner = :owner'
            )->setParameter('owner', $owner);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
