<?php

namespace Dk\Bundle\SystemBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CharacteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicRepository extends EntityRepository
{
}
