imports:
    - { resource: parameters_test.yml }
    - { resource: config_dev.yml }


framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
