homepage:
    pattern:   /
    defaults:  { _controller: DkPlayerBundle:Home:index }
    requirements:
        _method: GET
        
logout:
    pattern:   /logout
    
login_check:
    pattern:   /login_check

dk_player:
    resource: "@DkPlayerBundle/Resources/config/routing.yml"
    prefix:   /private/player
    
dk_character:
    resource: "@DkCharacterBundle/Resources/config/routing.yml"
    prefix:   /private/character    

dk_campaign:
    resource: "@DkCampaignBundle/Resources/config/routing.yml"
    prefix:   /private/campaign
    
dk_ruleset:
    resource: "@DkRulesetBundle/Resources/config/routing.yml"
    prefix:   /private/ruleset