lc_doctrine:
    resource: "@LcDoctrineBundle/Resources/config/routing.xml"
    prefix:   /

homepage:
    pattern:   /
    defaults:  { _controller: DkSystemBundle:Home:index }
        
logout:
    pattern:   /logout
    
login_check:
    pattern:   /login_check
      
dk_system:
    resource: "@DkSystemBundle/Resources/config/routing.yml"
    prefix:   /private
