homepage:
    pattern:   /
    defaults:  { _controller: DkPlayerBundle:Home:index }

login:
    pattern:   /login
    defaults:  { _controller: DkPlayerBundle:Security:login }
    
login_check:
    pattern:   /login_check

dk_player:
    resource: "@DkPlayerBundle/Resources/config/routing.yml"
    prefix:   /private/player

