security:
    encoders:
        Dk\PlayerBundle\Entity\Player:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        db:
            entity: { class: DkPlayerBundle:Player, property: email }
            
    firewalls:
        main:
            provider: db
            anonymous: ~
            pattern: ^/
            form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path: /private/player/all

    access_control:
        - { path: ^/private, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
