security:
    encoders:
        Dk\Bundle\SystemBundle\Entity\Player:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_MASTER_RULESET: ROLE_MASTER
        ROLE_MASTER: ROLE_PLAYER
        ROLE_ADMIN: [ROLE_PLAYER, ROLE_MASTER_RULSET, ROLE_ALLOWED_TO_SWITCH]

    providers:
        db:
            entity: { class: DkSystemBundle:Player, property: email }
            
    firewalls:
        main:
            provider: db
            anonymous: ~
            pattern: ^/
            form_login:
                login_path:  /
                check_path:  /login_check
                default_target_path: /private/board
                username_parameter: login[email]
                password_parameter: login[password]
            logout:
                path:   /logout
                target: /
                
    access_control:
        - { path: ^/private/player, roles: ROLE_PLAYER }
        - { path: ^/private/master, roles: ROLE_MASTER }
        - { path: ^/private/ruleset, roles: ROLE_MASTER_RULESET }
