board:
    path:   /board
    defaults:  { _controller: DkSystemBundle:Board:index }
    requirements:
        _method:  GET
        
_board:
    path:   /
    defaults:  { _controller: DkSystemBundle:Board:index }
    requirements:
        _method:  GET
        
player_account:
    path:   /account
    defaults:  { _controller: DkSystemBundle:Player:manage }

manage_pc:
    path:   /pc/{id}
    defaults:  { _controller: DkSystemBundle:Character:manage, id: null }
    requirements:
        id: \d+

manage_campaign:
    path:   /campaign/{id}
    defaults:  { _controller: DkSystemBundle:Campaign:manage, id: null }
    requirements:
        id: \d+