board:
    path:   /board
    defaults:  { _controller: DkSystemBundle:Board:index }
    requirements:
        _method:  GET

players:
    path:   /players
    defaults:  { _controller: DkSystemBundle:Player:showAll }
    requirements:
        _method:  GET

manage_player:
    path:   /player/{id}
    defaults:  { _controller: DkSystemBundle:Player:manage, id: null }
    requirements:
        id: \d+
        
manage_pc:
    path:   /pc/{id}
    defaults:  { _controller: DkSystemBundle:Character:manage, id: null }
    requirements:
        id: \d+
        
campaigns:
    path:   /campaigns
    defaults:  { _controller: DkSystemBundle:Campaign:showAll }
    requirements:
        _method:  GET

manage_campaign:
    path:   /campaign/{id}
    defaults:  { _controller: DkSystemBundle:Campaign:manage, id: null }
    requirements:
        id: \d+