parameters:
    pc.factory.class: Dk\Bundle\SystemBundle\Factory\PlayerCharacterFactory
    campaign.factory.class: Dk\Bundle\SystemBundle\Factory\CampaignFactory    

services:
    dk_pc_factory:
        class:  "%pc.factory.class%"
        arguments:    ["@=service('security.context').getToken().getUser()"]
    dk_campaign_factory:
        class:  "%campaign.factory.class%"
        arguments:    ["@=service('security.context').getToken().getUser()"]
    dk.type.plain_text:
        class: Dk\Bundle\SystemBundle\Form\Type\PlainTextType
        tags:
            - { name: form.type, alias: plain_text }        