<?php

namespace Dk\PlayerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    /**
     * Get all players joined by their characters
     * @return mixed
     */
    public function findWithCharacters()
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p, pc, c FROM DkPlayerBundle:Player p
                LEFT JOIN p.characters pc
                LEFT JOIN pc.campaign c'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
